name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make
    - name: make run
      run: cd build && make run
